// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelFarm.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModelFarm.Infrastructure.Persistence.Migrations.Data
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260129130158_AddDatasetAndConfigTypes")]
    partial class AddDatasetAndConfigTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.DatasetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time_utc");

                    b.Property<int>("Exchange")
                        .HasColumnType("integer")
                        .HasColumnName("exchange");

                    b.Property<Guid?>("IngestionOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_operation_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_datasets");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_datasets_name");

                    b.ToTable("datasets", "data");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.KlineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("close");

                    b.Property<long>("CloseTime")
                        .HasColumnType("bigint")
                        .HasColumnName("close_time");

                    b.Property<int>("Exchange")
                        .HasColumnType("integer")
                        .HasColumnName("exchange");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("high");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("low");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_trades");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("open");

                    b.Property<long>("OpenTime")
                        .HasColumnType("bigint")
                        .HasColumnName("open_time");

                    b.Property<decimal>("QuoteAssetVolume")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("quote_asset_volume");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_klines");

                    b.HasIndex("Exchange", "Symbol", "Interval", "OpenTime")
                        .IsUnique()
                        .HasDatabaseName("ix_klines_exchange_symbol_interval_open_time");

                    b.HasIndex("Exchange", "Symbol", "Interval", "OpenTime", "CloseTime")
                        .HasDatabaseName("ix_klines_exchange_symbol_interval_open_time_close_time");

                    b.ToTable("klines", "data");
                });
#pragma warning restore 612, 618
        }
    }
}
