// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelFarm.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModelFarm.Infrastructure.Persistence.Migrations.App
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202102154_AddResourceQueuesWithContainerRefs")]
    partial class AddResourceQueuesWithContainerRefs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.BackgroundTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parameters_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<long>("ProgressCurrent")
                        .HasColumnType("bigint")
                        .HasColumnName("progress_current");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("progress_message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<long>("ProgressTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("progress_total");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_background_tasks");

                    b.HasIndex("RelatedEntityId")
                        .HasDatabaseName("ix_background_tasks_related_entity_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_background_tasks_status");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc")
                        .HasDatabaseName("ix_background_tasks_status_priority_created_at_utc");

                    b.ToTable("background_tasks", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.ModelTestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dataset_name");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ModelJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_job_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_model_tests");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_model_tests_created_at_utc");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_model_tests_dataset_id");

                    b.HasIndex("ModelJobId")
                        .HasDatabaseName("ix_model_tests_model_job_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_model_tests_status");

                    b.ToTable("model_tests", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.ResourceContainerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_resource_containers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_resource_containers_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_resource_containers_type");

                    b.HasIndex("Type", "IsDefault")
                        .HasDatabaseName("ix_resource_containers_type_is_default");

                    b.ToTable("resource_containers", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.ResourceQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CpuContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cpu_container_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("GpuContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("gpu_container_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_jobs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resource_queues");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("ix_resource_queues_is_default");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_resource_queues_name");

                    b.ToTable("resource_queues", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.TrainingConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("batch_size");

                    b.Property<int>("CheckpointIntervalEpochs")
                        .HasColumnType("integer")
                        .HasColumnName("checkpoint_interval_epochs");

                    b.Property<Guid?>("CpuContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cpu_container_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<double>("DropoutRate")
                        .HasColumnType("double precision")
                        .HasColumnName("dropout_rate");

                    b.Property<int>("EarlyStoppingPatience")
                        .HasColumnType("integer")
                        .HasColumnName("early_stopping_patience");

                    b.Property<int>("ForecastHorizon")
                        .HasColumnType("integer")
                        .HasColumnName("forecast_horizon");

                    b.Property<Guid?>("GpuContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("gpu_container_id");

                    b.Property<string>("HiddenLayerSizesJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hidden_layer_sizes_json");

                    b.Property<double>("LearningRate")
                        .HasColumnType("double precision")
                        .HasColumnName("learning_rate");

                    b.Property<double>("LearningRateRetryScale")
                        .HasColumnType("double precision")
                        .HasColumnName("learning_rate_retry_scale");

                    b.Property<int>("MaxEpochs")
                        .HasColumnType("integer")
                        .HasColumnName("max_epochs");

                    b.Property<int>("MaxLags")
                        .HasColumnType("integer")
                        .HasColumnName("max_lags");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_retry_attempts");

                    b.Property<int>("ModelType")
                        .HasColumnType("integer")
                        .HasColumnName("model_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PerformanceRequirementsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("performance_requirements_json");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer")
                        .HasColumnName("random_seed");

                    b.Property<bool>("RetryUntilSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("retry_until_success");

                    b.Property<bool>("SaveCheckpoints")
                        .HasColumnType("boolean")
                        .HasColumnName("save_checkpoints");

                    b.Property<bool>("ScaleLearningRateOnRetry")
                        .HasColumnType("boolean")
                        .HasColumnName("scale_learning_rate_on_retry");

                    b.Property<bool>("ShuffleOnRetry")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_on_retry");

                    b.Property<double>("TestSplit")
                        .HasColumnType("double precision")
                        .HasColumnName("test_split");

                    b.Property<string>("TradingEnvironmentJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("trading_environment_json");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<bool>("UseEarlyStopping")
                        .HasColumnType("boolean")
                        .HasColumnName("use_early_stopping");

                    b.Property<bool>("UseGpuForInference")
                        .HasColumnType("boolean")
                        .HasColumnName("use_gpu_for_inference");

                    b.Property<double>("ValidationSplit")
                        .HasColumnType("double precision")
                        .HasColumnName("validation_split");

                    b.HasKey("Id")
                        .HasName("pk_training_configurations");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_training_configurations_created_at_utc");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_training_configurations_dataset_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_training_configurations_name");

                    b.ToTable("training_configurations", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.TrainingJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AccumulatedTrainingTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("accumulated_training_ticks");

                    b.Property<double?>("BestValidationLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("best_validation_loss");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("current_attempt");

                    b.Property<int>("CurrentEpoch")
                        .HasColumnType("integer")
                        .HasColumnName("current_epoch");

                    b.Property<int>("EpochsSinceImprovement")
                        .HasColumnType("integer")
                        .HasColumnName("epochs_since_improvement");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<bool>("HasCheckpoint")
                        .HasColumnType("boolean")
                        .HasColumnName("has_checkpoint");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<DateTime?>("LastCheckpointAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checkpoint_at_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalEpochs")
                        .HasColumnType("integer")
                        .HasColumnName("total_epochs");

                    b.Property<double?>("TrainingLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("training_loss");

                    b.Property<double?>("ValidationLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("validation_loss");

                    b.HasKey("Id")
                        .HasName("pk_training_jobs");

                    b.HasIndex("ConfigurationId")
                        .HasDatabaseName("ix_training_jobs_configuration_id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_training_jobs_created_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_training_jobs_status");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_training_jobs_status_created_at_utc");

                    b.ToTable("training_jobs", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.UserAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at_utc");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_access");

                    b.HasIndex("AccessedAtUtc")
                        .HasDatabaseName("ix_user_access_accessed_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_access_user_id");

                    b.ToTable("user_access", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.UserOwnershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_ownerships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_ownerships_user_id");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_user_ownerships_resource_type_resource_id");

                    b.HasIndex("UserId", "ResourceType")
                        .HasDatabaseName("ix_user_ownerships_user_id_resource_type");

                    b.ToTable("user_ownerships", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
