// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelFarm.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModelFarm.Infrastructure.Persistence.Migrations.App
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131081125_AddConfigCheckpointAndRetryFields")]
    partial class AddConfigCheckpointAndRetryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.BackgroundTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parameters_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<long>("ProgressCurrent")
                        .HasColumnType("bigint")
                        .HasColumnName("progress_current");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("progress_message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<long>("ProgressTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("progress_total");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_background_tasks");

                    b.HasIndex("RelatedEntityId")
                        .HasDatabaseName("ix_background_tasks_related_entity_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_background_tasks_status");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc")
                        .HasDatabaseName("ix_background_tasks_status_priority_created_at_utc");

                    b.ToTable("background_tasks", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.TrainingConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("batch_size");

                    b.Property<int>("CheckpointIntervalEpochs")
                        .HasColumnType("integer")
                        .HasColumnName("checkpoint_interval_epochs");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<double>("DropoutRate")
                        .HasColumnType("double precision")
                        .HasColumnName("dropout_rate");

                    b.Property<int>("EarlyStoppingPatience")
                        .HasColumnType("integer")
                        .HasColumnName("early_stopping_patience");

                    b.Property<int>("ForecastHorizon")
                        .HasColumnType("integer")
                        .HasColumnName("forecast_horizon");

                    b.Property<string>("HiddenLayerSizesJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hidden_layer_sizes_json");

                    b.Property<double>("LearningRate")
                        .HasColumnType("double precision")
                        .HasColumnName("learning_rate");

                    b.Property<double>("LearningRateRetryScale")
                        .HasColumnType("double precision")
                        .HasColumnName("learning_rate_retry_scale");

                    b.Property<int>("MaxEpochs")
                        .HasColumnType("integer")
                        .HasColumnName("max_epochs");

                    b.Property<int>("MaxLags")
                        .HasColumnType("integer")
                        .HasColumnName("max_lags");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_retry_attempts");

                    b.Property<int>("ModelType")
                        .HasColumnType("integer")
                        .HasColumnName("model_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PerformanceRequirementsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("performance_requirements_json");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer")
                        .HasColumnName("random_seed");

                    b.Property<bool>("RetryUntilSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("retry_until_success");

                    b.Property<bool>("SaveCheckpoints")
                        .HasColumnType("boolean")
                        .HasColumnName("save_checkpoints");

                    b.Property<bool>("ScaleLearningRateOnRetry")
                        .HasColumnType("boolean")
                        .HasColumnName("scale_learning_rate_on_retry");

                    b.Property<bool>("ShuffleOnRetry")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_on_retry");

                    b.Property<double>("TestSplit")
                        .HasColumnType("double precision")
                        .HasColumnName("test_split");

                    b.Property<string>("TradingEnvironmentJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("trading_environment_json");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<double>("ValidationSplit")
                        .HasColumnType("double precision")
                        .HasColumnName("validation_split");

                    b.HasKey("Id")
                        .HasName("pk_training_configurations");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_training_configurations_created_at_utc");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_training_configurations_dataset_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_training_configurations_name");

                    b.ToTable("training_configurations", "app");
                });

            modelBuilder.Entity("ModelFarm.Infrastructure.Persistence.Entities.TrainingJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AccumulatedTrainingTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("accumulated_training_ticks");

                    b.Property<double?>("BestValidationLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("best_validation_loss");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("current_attempt");

                    b.Property<int>("CurrentEpoch")
                        .HasColumnType("integer")
                        .HasColumnName("current_epoch");

                    b.Property<int>("EpochsSinceImprovement")
                        .HasColumnType("integer")
                        .HasColumnName("epochs_since_improvement");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExecutionOptionsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("execution_options_json");

                    b.Property<bool>("HasCheckpoint")
                        .HasColumnType("boolean")
                        .HasColumnName("has_checkpoint");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<DateTime?>("LastCheckpointAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checkpoint_at_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OverridesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("overrides_json");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalEpochs")
                        .HasColumnType("integer")
                        .HasColumnName("total_epochs");

                    b.Property<double?>("TrainingLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("training_loss");

                    b.Property<double?>("ValidationLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("validation_loss");

                    b.HasKey("Id")
                        .HasName("pk_training_jobs");

                    b.HasIndex("ConfigurationId")
                        .HasDatabaseName("ix_training_jobs_configuration_id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_training_jobs_created_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_training_jobs_status");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_training_jobs_status_created_at_utc");

                    b.ToTable("training_jobs", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
